import Papa from 'papaparse';

// Raw CSV string embedded as fail-safe fallback to guarantee immediate offline/Vite reactivity
export const embeddedCSVData = `Timestamp,Email Address,"Privacy Notice","Full Name","Student ID","Degree Program","Year of Graduation","Capstone Role","Rate Core Programming","Rate Electives","Rate Mentorship","Rate Internship","Useful Tech Taught","Missing Tech Desired","Rate Hardware Specs","Rate Software IDEs","Rate Campus Internet","Rate Lab Cleanliness Aircon","Biggest Lab Grievance","Employment Status","Confidence Tech Interviews","Willing Guest Speaker","Rewarding Breakthrough","Restructure CCS Process","Legacy Tip For Freshmen"
"2026-07-16 18:42:12","nnericua99@gmail.com","Yes","Nericua Nicole D.","0122-0783","BS in Information Technology (BSIT)","2026","QA Tester / Technical Documentation Specialist","5","5","5","4","python","modern frameworks","4","3","4","4","Hardware Resource Constraints","Employed full-time as a Tech Professional","Moderately Confident","Undecided","The most rewarding experience was when we finally got our system prototype to run completely error-free after sleepless nights of debugging.","defense schedule","Don't waste your time memorizing syntax learn how to Google properly"
"2026-07-16 19:31:07","almariocelrick@gmail.com","Yes","Almario Cel Rick D.","0122-1123","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","3","4","4","Python","Cybersecurity","4","4","4","4","Specs","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Computer Vision","N/A","Don't rely too much on AI."
"2026-07-16 19:37:15","anonuevochrist.09@gmail.com","Yes","Añonuevo Maria Christina G.","0122-0417","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","5","5","5","5","Python Java HTML CSS JavaScript SQL Git and VS Code","Cloud computing DevOps modern web frameworks","5","4","4","4","Slow performance of some lab PCs and internet connectivity","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Completing a difficult coding project after overcoming numerous bugs","Organize project defense process earlier","Be patient and keep coding. Every programmer starts as a beginner."
"2026-07-16 20:03:15","rianaalexisbagalso@gmail.com","Yes","Bagalso Riana Alexis C.","0122-1097","BS in Computer Science (BSCS)","2026","QA Tester / Technical Documentation Specialist","4","4","4","4","Python","Adobe tools","4","4","3","4","The internet sometimes doesn't work.","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Passing the final defense","None","None"
"2026-07-17 9:57:17","angeloaquino38@gmail.com","Yes","Aquino Angelo D.","0122-0242","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","5","3","4","Python Java MySQL HTML/CSS/JS","Modern frontend frameworks like React Next.js or Vue.js","3","4","2","3","Limited booking availability for computer labs during project crunch weeks.","Unemployed but actively applying for tech positions / Upskilling","Very Confident","Yes definitely","Passing our final capstone defense after months of intensive coding","Standardizing and releasing defense schedules earlier","Learn Git version control early—it will save your group projects from disaster."
"2026-07-17 11:08:20","nathaliesantiago45@gmail.com","Yes","Santiago Nathalie G.","0122-0259","BS in Information Technology (BSIT)","2026","UI/UX Designer / Frontend Developer","3","4","4","4","Python for data analysis and machine learning plus SQL for backend","Cloud platforms like AWS or Google Cloud Docker and DevOps CI/CD pipelines","4","4","5","4","Limited booking availability for computer labs during project crunch weeks.","Employed full-time as a Tech Professional","Moderately Confident","Undecided","Building an end-to-end full-stack web application from scratch","Improving student-faculty communication channels for thesis feedback","Don't rely solely on AI to write your code. Use it as a tutor."
"2026-07-17 12:44:31","johnmarkbautista82@gmail.com","Yes","Bautista John Mark M.","0122-0181","BS in Information Technology (BSIT)","2026","Project Manager / System Analyst","5","4","4","5","Python C++ PHP and SQL databases","Cybersecurity fundamentals ethical hacking and network security tools","3","5","4","5","Outdated hardware specifications on some PC workstations causing slow compilation","Employed full-time as a Tech Professional","Moderately Confident","Maybe / Undecided","Successfully debugging a critical memory leak and database sync issue","Standardizing and releasing defense schedules earlier","Master the fundamental logic and problem-solving skills first."
"2026-07-17 13:22:45","samanthabeltran90@gmail.com","Yes","Beltran Samantha P.","0122-0284","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","4","3","4","5","Python Java Git and Visual Studio Code","Containerization tools like Docker and Kubernetes","4","4","3","4","Slow boot times on HDD-based workstations; upgrading to SSDs would help","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Building an end-to-end full-stack web application from scratch","Offering more hands-on elective subjects aligned with specialized tech tracks","Start building personal projects early and host them on GitHub."
"2026-07-17 14:15:10","gwenalvarez54@gmail.com","Yes","Alvarez Gwen C.","0122-0542","BS in Computer Science (BSCS)","2026","QA Tester / Technical Documentation Specialist","4","4","5","4","JavaScript PHP Laravel framework and MySQL","DevOps practices Docker containers and CI/CD tools","5","3","4","4","Air conditioning unit malfunctions in PC Lab 2 making long coding uncomfortable","Unemployed but actively applying for tech positions / Upskilling","Very Confident","Yes as a guest speaker","Passing our final capstone defense after months of intensive coding","Streamlining the rubric and criteria for Capstone project evaluation","Learn Git version control early—it will save your group projects."
"2026-07-18 9:12:30","ethangarcia12@gmail.com","Yes","Garcia Ethan B.","0122-0312","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","5","4","3","4","Java Python C# and relational database management (MySQL/PostgreSQL)","Mobile app development using Flutter or React Native","3","4","3","3","Intermittent campus Wi-Fi connectivity and high network latency","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Deploying our capstone project live on a cloud server","Upgrading the computer lab reservation system to an online portal","Choose reliable capstone team members who share your work ethic."
"2026-07-18 10:45:18","kylecastillo67@gmail.com","Yes","Castillo Kyla A.","0122-0811","BS in Computer Science (BSCS)","2026","Data Analyst / Machine Learning Developer","4","5","4","5","Python for data analysis and machine learning plus SQL for backend","AI/ML frameworks like PyTorch or TensorFlow integrated deeper","4","5","4","4","Insufficient GPU capabilities for heavy training of computer vision models","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Integrating a real-time machine learning model with our web application backend","Offering more hands-on elective subjects aligned with specialized tech tracks","Don't be afraid to break things and debug. Read error logs."
"2026-07-18 12:05:40","christianreyes22@gmail.com","Yes","Reyes Christian D.","0122-0129","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","4","4","5","4","React Node.js JavaScript Python and Git","Cloud computing microservices architecture and API gateway integration","3","4","2","4","Strict server access restrictions making it difficult to host and test","Employed part-time / Freelancing","Moderately Confident","Maybe / Undecided","Fixing a persistent API integration bug after a full night of trial and error","Simplifying lab clearance protocols and software installation requests","Consistency over cramming. Practice coding for at least 30 to 60 minutes daily."
"2026-07-18 13:48:12","erikadiaz89@gmail.com","Yes","Diaz Erika L.","0122-0891","BS in Information Technology (BSIT)","2026","UI/UX Designer / Frontend Developer","4","4","4","5","JavaScript Vue.js Tailwind CSS and Node.js","Modern frontend frameworks like React Next.js or Vue.js","4","4","3","4","Outdated hardware specifications on some PC workstations causing slow compilation","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Yes definitely","Building an end-to-end full-stack web application from scratch","Improving student-faculty communication channels for thesis feedback","Master the fundamental logic and problem-solving skills first."
"2026-07-18 14:30:22","justinflores33@gmail.com","Yes","Flores Justin M.","0122-0331","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","5","4","4","C# and .NET framework along with SQL Server","Cloud platforms like AWS or Google Cloud Docker and DevOps CI/CD pipelines","3","4","4","4","Limited admin privileges on lab computers preventing installation of necessary dev packages","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Successfully debugging a critical memory leak and database sync issue","Standardizing and releasing defense schedules earlier","Learn Git version control early—it will save your group projects."
"2026-07-18 15:18:50","daveocampo78@gmail.com","Yes","Ocampo Dave R.","0122-0782","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","4","3","5","5","HTML CSS JavaScript PHP and MySQL for full-stack web development","DevOps practices Docker containers and CI/CD tools","4","3","3","4","Slow boot times on HDD-based workstations; upgrading to SSDs would help","Employed full-time as a Tech Professional","Moderately Confident","Undecided","Deploying our capstone project live on a cloud server","Upgrading the computer lab reservation system to an online self-service portal","Consistency over cramming. Practice coding regularly."
"2026-07-19 9:25:11","patriciaserano14@gmail.com","Yes","Serrano Patricia S.","0122-0145","BS in Computer Science (BSCS)","2026","Data Analyst / Machine Learning Developer","5","4","5","4","Python for data analysis and machine learning plus SQL","AI/ML frameworks like PyTorch or TensorFlow integrated deeper","4","4","4","5","Insufficient GPU capabilities for heavy training of computer vision models","Employed full-time as a Tech Professional","Extremely Confident","Yes as a guest speaker","Integrating a real-time machine learning model with our web backend","Offering more hands-on elective subjects","Don't be afraid to break things and debug. Read error logs."
"2026-07-19 10:40:05","gabrielnavarro62@gmail.com","Yes","Navarro Gabriel T.","0122-0621","BS in Information Technology (BSIT)","2026","Project Manager / System Analyst","3","4","4","4","Python Flask React Native and Git version control","Cloud computing microservices architecture and API gateway integration","3","4","2","3","Strict server access restrictions making it difficult to host","Unemployed but actively applying for tech positions / Upskilling","Slightly Confident","Maybe / Undecided","Passing our final capstone defense after months of intensive coding","Streamlining the rubric and criteria for Capstone project evaluation","Choose reliable capstone team members who share your work ethic."
"2026-07-19 11:55:42","kathleenperez19@gmail.com","Yes","Perez Kathleen A.","0122-0193","BS in Computer Science (BSCS)","2026","QA Tester / Technical Documentation Specialist","4","4","3","5","Java OOP concepts Python scripting and SQL database design","Containerization tools like Docker and Kubernetes","4","4","4","4","Intermittent campus Wi-Fi connectivity and high network latency","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Overcoming complex recursive algorithm and data structure problems","Simplifying lab clearance protocols and software installation requests","Start building personal projects early and host them on GitHub."
"2026-07-19 13:10:15","francissalazar51@gmail.com","Yes","Salazar Francis V.","0122-0518","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","5","4","4","4","Python Java MySQL and REST API development principles","Cybersecurity fundamentals ethical hacking and network security tools","4","4","3","4","Occasional power fluctuation or loss of connection to local servers","Employed part-time / Freelancing","Moderately Confident","Undecided","Fixing a persistent API integration bug after a full night of trial and error","Standardizing and releasing defense schedules earlier","Don't rely solely on AI to write your code. Use it as a tutor."
"2026-07-19 14:22:38","chloemendoza03@gmail.com","Yes","Mendoza Chloe E.","0122-0034","BS in Information Technology (BSIT)","2026","UI/UX Designer / Frontend Developer","4","3","5","4","JavaScript Vue.js Tailwind CSS and Node.js","Mobile app development using Flutter or React Native","3","3","4","4","Air conditioning unit malfunctions in PC Lab 2","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Yes definitely","Building an end-to-end full-stack web application from scratch","Upgrading the computer lab reservation system to an online self-service portal","Learn Git version control early—it will save your group projects."
"2026-07-20 9:14:50","adrianramos77@gmail.com","Yes","Ramos Adrian C.","0122-0772","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","5","4","5","Python C++ and database management systems","DevOps practices Docker containers and CI/CD tools","4","5","3","4","Limited admin privileges on lab computers preventing software setup","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Successfully debugging a critical memory leak and database sync issue","Offering more hands-on elective subjects","Master fundamental logic and problem solving first."
"2026-07-20 10:35:12","janinemanalo88@gmail.com","Yes","Manalo Janine B.","0122-0885","BS in Information Technology (BSIT)","2026","QA Tester / Technical Documentation Specialist","4","4","4","4","Python Java MySQL and HTML/CSS/JS","Version control workflows (advanced Git/GitHub Actions) and Agile tools","3","4","4","4","Outdated hardware specifications on some PC workstations","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Passing our final capstone defense after months of intensive coding","Improving student-faculty communication channels for thesis feedback","Choose reliable capstone team members who share your work ethic."
"2026-07-20 11:50:29","johnpauldizon63@gmail.com","Yes","Dizon John Paul M.","0122-0639","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","4","4","5","4","Java Python C# and relational database management","Cloud platforms like AWS or Google Cloud Docker and DevOps pipelines","4","4","3","4","Strict server access restrictions making it difficult to host","Employed full-time as a Tech Professional","Very Confident","Yes as a guest speaker","Deploying our capstone project live on a cloud server","Standardizing and releasing defense schedules earlier","Consistency over cramming. Practice coding regularly."
"2026-07-20 13:05:44","andreaaquino29@gmail.com","Yes","Aquino Andrea G.","0122-0291","BS in Computer Science (BSCS)","2026","UI/UX Designer / Frontend Developer","3","3","4","4","React Node.js JavaScript Python and Git","Modern frontend frameworks like React Next.js or Vue.js","3","3","4","3","Slow boot times on HDD-based workstations","Unemployed but actively applying for tech positions / Upskilling","Slightly Confident","Maybe / Undecided","Building an end-to-end full-stack web application from scratch","Upgrading the computer lab reservation system to an online portal","Don't rely solely on AI to write your code. Write logic yourself."
"2026-07-20 14:18:02","kennethagoncillo11@gmail.com","Yes","Agoncillo Kenneth T.","0122-0114","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","5","4","4","5","Python Flask React Native and Git","Cloud infrastructure management (AWS Azure) and modern backend frameworks","4","4","4","4","Limited booking availability for computer labs during project crunch weeks.","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Fixing a persistent API integration bug after a full night of trial and error","Offering more hands-on elective subjects","Learn Git version control early—it will save your group projects."
"2026-07-21 9:30:15","jasminesoriano95@gmail.com","Yes","Soriano Jasmine F.","0122-0952","BS in Computer Science (BSCS)","2026","Data Analyst / Machine Learning Developer","5","5","5","4","Python for data analysis and machine learning plus SQL","AI/ML frameworks like PyTorch or TensorFlow integrated deeper","5","4","5","5","Insufficient GPU capabilities for heavy training of computer vision models","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Integrating a real-time machine learning model with our web application backend","Streamlining the rubric and criteria for Capstone project evaluation","Don't be afraid to break things and debug. Read error logs."
"2026-07-21 10:42:33","ivandelacruz47@gmail.com","Yes","Dela Cruz Ivan R.","0122-0473","BS in Information Technology (BSIT)","2026","Project Manager / System Analyst","4","4","3","4","Python C++ PHP and SQL databases","Cybersecurity fundamentals ethical hacking and network security tools","3","4","3","3","Intermittent campus Wi-Fi connectivity and high network latency","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Passing our final capstone defense after months of intensive coding","Improving student-faculty communication channels for thesis feedback","Master fundamental logic and problem-solving skills first."
"2026-07-21 11:58:10","clarisseluna81@gmail.com","Yes","Luna Clarisse M.","0122-0819","BS in Information Technology (BSIT)","2026","QA Tester / Technical Documentation Specialist","4","3","4","4","Java OOP concepts Python scripting and SQL database design","Containerization tools like Docker and Kubernetes","4","4","4","4","Outdated hardware specifications on some PC workstations","Employed full-time as a Tech Professional","Moderately Confident","Yes as a guest speaker","Overcoming complex recursive algorithm and data structure problems","Simplifying lab clearance protocols and software installation requests","Choose reliable capstone team members who share your work ethic."
"2026-07-21 13:12:45","derricktorres36@gmail.com","Yes","Torres Derrick L.","0122-0364","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","4","5","5","Python Java MySQL and REST API development principles","Cloud platforms like AWS or Google Cloud Docker and DevOps pipelines","4","4","3","4","Occasional power fluctuation or loss of connection to local servers","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Successfully debugging a critical memory leak and database sync issue","Standardizing and releasing defense schedules earlier","Start building personal projects early and host them on GitHub."
"2026-07-21 14:25:01","paolocastillo23@gmail.com","Yes","Castillo Paolo D.","0122-0238","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","4","4","4","4","HTML CSS JavaScript PHP and MySQL for full-stack web development","DevOps practices Docker containers and CI/CD tools","3","3","4","4","Air conditioning unit malfunctions in PC Lab 2","Employed part-time / Freelancing","Moderately Confident","Maybe / Undecided","Deploying our capstone project live on a cloud server","Upgrading the computer lab reservation system to an online portal","Consistency over cramming. Practice coding regularly."
"2026-07-22 9:10:44","hannahmercado56@gmail.com","Yes","Mercado Hannah V.","0122-0562","BS in Computer Science (BSCS)","2026","UI/UX Designer / Frontend Developer","4","4","5","5","JavaScript Vue.js Tailwind CSS and Node.js","Modern frontend frameworks like React Next.js or Vue.js","4","4","4","4","Slow boot times on HDD-based workstations","Unemployed but actively applying for tech positions / Upskilling","Very Confident","Yes definitely","Building an end-to-end full-stack web application from scratch","Offering more hands-on elective subjects aligned with specialized tech tracks","Learn Git version control early—it will save your group projects."
"2026-07-22 10:22:18","camillevillanueva17@gmail.com","Yes","Villanueva Camille P.","0122-0176","BS in Information Technology (BSIT)","2026","Project Manager / System Analyst","3","4","4","4","Python Flask React Native and Git version control","Mobile app development using Flutter or React Native","3","4","3","3","Limited booking availability for computer labs during crunch weeks","Employed full-time as a Tech Professional","Moderately Confident","Undecided","Fixing a persistent API integration bug after a full night of trial and error","Improving student-faculty communication channels for thesis feedback","Master fundamental logic and problem-solving skills first."
"2026-07-22 11:35:50","renzagoncillo09@gmail.com","Yes","Agoncillo Renz J.","0122-0094","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","5","4","5","Python C++ and database management systems","Cloud computing microservices architecture and API gateway integration","4","5","4","4","Limited admin privileges on lab computers preventing software setup","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Successfully debugging a critical memory leak and database sync issue","Standardizing and releasing defense schedules earlier","Don't rely solely on AI to write your code. Use it as a tutor."
"2026-07-22 12:48:02","tristanpineda73@gmail.com","Yes","Pineda Tristan K.","0122-0731","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","4","4","3","4","Java Python C# and relational database management","Version control workflows and Agile/Scrum project tools","3","4","3","4","Strict server access restrictions making it difficult to host","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Maybe / Undecided","Deploying our capstone project live on a cloud server","Simplifying lab clearance protocols and software installation requests","Consistency over cramming. Practice coding regularly."
"2026-07-22 14:02:19","bryangalvez64@gmail.com","Yes","Galvez Bryan M.","0122-0648","BS in Information Technology (BSIT)","2026","QA Tester / Technical Documentation Specialist","4","3","4","4","Python Java Git and Visual Studio Code","Containerization tools like Docker and Kubernetes","4","3","4","4","Outdated hardware specifications on some PC workstations","Employed full-time as a Tech Professional","Moderately Confident","Yes as a guest speaker","Passing our final capstone defense after months of intensive coding","Streamlining the rubric and criteria for Capstone project evaluation","Choose reliable capstone team members who share your work ethic."
"2026-07-23 9:15:33","lestervalenzuela83@gmail.com","Yes","Valenzuela Lester R.","0122-0834","BS in Computer Science (BSCS)","2026","Data Analyst / Machine Learning Developer","5","4","5","5","Python for data analysis and machine learning plus SQL","AI/ML frameworks like PyTorch or TensorFlow integrated deeper","4","4","4","5","Insufficient GPU capabilities for heavy training of computer vision models","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Integrating a real-time machine learning model with our web application backend","Offering more hands-on elective subjects","Don't be afraid to break things and debug. Read error logs."
"2026-07-23 10:28:10","jeromederosario42@gmail.com","Yes","Del Rosario Jerome C.","0122-0428","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","4","5","4","4","React Node.js JavaScript Python and Git","Cloud infrastructure management (AWS Azure) and modern backend frameworks","3","4","2","3","Intermittent campus Wi-Fi connectivity and high network latency","Unemployed but actively applying for tech positions / Upskilling","Very Confident","Undecided","Fixing a persistent API integration bug after a full night of trial and error","Upgrading the computer lab reservation system to an online self-service portal","Learn Git version control early—it will save your group projects."
"2026-07-23 11:40:25","daphnesantiago39@gmail.com","Yes","Santiago Daphne E.","0122-0395","BS in Computer Science (BSCS)","2026","UI/UX Designer / Frontend Developer","4","4","5","4","JavaScript Vue.js Tailwind CSS and Node.js","Modern frontend frameworks like React Next.js or Vue.js","4","4","3","4","Air conditioning unit malfunctions in PC Lab 2","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Building an end-to-end full-stack web application from scratch","Improving student-faculty communication channels for thesis feedback","Start building personal projects early and host them on GitHub."
"2026-07-23 12:52:11","kimberlyagoncillo66@gmail.com","Yes","Agoncillo Kimberly L.","0122-0661","BS in Information Technology (BSIT)","2026","Project Manager / System Analyst","3","3","4","4","Python C++ PHP and SQL databases","Cybersecurity fundamentals ethical hacking and network security tools","3","3","4","3","Limited booking availability for computer labs during crunch weeks","Pursuing continuous certifications or graduate degrees (MSCS / MSIT)","Slightly Confident","Maybe / Undecided","Passing our final capstone defense after months of intensive coding","Standardizing and releasing defense schedules earlier","Master fundamental logic and problem-solving skills first."
"2026-07-23 14:05:44","markanthonyespiritu28@gmail.com","Yes","Espiritu Mark Anthony D.","0122-0289","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","4","4","3","5","HTML CSS JavaScript PHP and MySQL for full-stack web development","Cloud platforms like AWS or Google Cloud Docker and DevOps pipelines","4","4","3","4","Occasional power fluctuation or loss of connection to local servers","Employed full-time as a Tech Professional","Moderately Confident","Yes as a guest speaker","Deploying our capstone project live on a cloud server","Simplifying lab clearance protocols and software installation requests","Consistency over cramming. Practice coding regularly."
"2026-07-24 9:20:05","derekbautista91@gmail.com","Yes","Bautista Derrick F.","0122-0912","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","5","5","4","Python Java MySQL and REST API development principles","DevOps practices Docker containers and CI/CD tools","4","5","4","4","Slow boot times on HDD-based workstations","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Successfully debugging a critical memory leak and database sync issue","Offering more hands-on elective subjects","Don't rely solely on AI to write your code. Use it as a tutor."
"2026-07-24 10:32:19","julianserano74@gmail.com","Yes","Serrano Julian K.","0122-0743","BS in Information Technology (BSIT)","2026","QA Tester / Technical Documentation Specialist","4","3","4","4","Java OOP concepts Python scripting and SQL database design","Containerization tools like Docker and Kubernetes","3","4","4","3","Outdated hardware specifications on some PC workstations","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Overcoming complex recursive algorithm and data structure problems","Streamlining the rubric and criteria for Capstone project evaluation","Choose reliable capstone team members who share your work ethic."
"2026-07-24 11:45:02","ellarivera53@gmail.com","Yes","Rivera Ella P.","0122-0538","BS in Computer Science (BSCS)","2026","Data Analyst / Machine Learning Developer","5","4","4","5","Python for data analysis and machine learning plus SQL","AI/ML frameworks like PyTorch or TensorFlow integrated deeper","4","4","4","5","Insufficient GPU capabilities for heavy training of computer vision models","Employed full-time as a Tech Professional","Very Confident","Yes definitely","Integrating a real-time machine learning model with our web backend","Upgrading the computer lab reservation system to an online self-service portal","Don't be afraid to break things and debug. Read error logs."
"2026-07-24 12:58:30","joshuagonzales15@gmail.com","Yes","Gonzales Joshua M.","0122-0157","BS in Information Technology (BSIT)","2026","UI/UX Designer / Frontend Developer","4","4","5","4","JavaScript Vue.js Tailwind CSS and Node.js","Mobile app development using Flutter or React Native","3","3","3","4","Air conditioning unit malfunctions in PC Lab 2","Employed part-time / Freelancing","Moderately Confident","Maybe / Undecided","Building an end-to-end full-stack web application from scratch","Improving student-faculty communication channels for thesis feedback","Learn Git version control early—it will save your group projects."
"2026-07-24 14:12:08","angelicaguerrero86@gmail.com","Yes","Guerrero Angelica B.","0122-0864","BS in Information Technology (BSIT)","2026","Lead Developer / Programmer","4","5","4","4","Python Flask React Native and Git version control","Cloud computing microservices architecture and API gateway integration","4","4","2","3","Strict server access restrictions making it difficult to host","Employed full-time as a Tech Professional","Very Confident","Yes as a guest speaker","Fixing a persistent API integration bug after a full night of trial and error","Standardizing and releasing defense schedules earlier","Master fundamental logic and problem-solving skills first."
"2026-07-25 9:18:40","beatolentino27@gmail.com","Yes","Tolentino Bea R.","0122-0275","BS in Computer Science (BSCS)","2026","Project Manager / System Analyst","3","3","4","4","Python C++ PHP and SQL databases","Version control workflows and Agile/Scrum project tools","3","4","3","4","Intermittent campus Wi-Fi connectivity and high network latency","Unemployed but actively applying for tech positions / Upskilling","Slightly Confident","Undecided","Passing our final capstone defense after months of intensive coding","Simplifying lab clearance protocols and software installation requests","Start building personal projects early and host them on GitHub."
"2026-07-25 10:31:14","alyssasantiago92@gmail.com","Yes","Santiago Alyssa G.","0122-0923","BS in Information Technology (BSIT)","2026","Backend Developer / Database Administrator","4","4","3","5","Java Python C# and relational database management","Cloud infrastructure management (AWS Azure) and modern backend frameworks","4","4","3","4","Limited admin privileges on lab computers preventing software setup","Employed full-time as a Tech Professional","Moderately Confident","Yes definitely","Deploying our capstone project live on a cloud server","Offering more hands-on elective subjects","Consistency over cramming. Practice coding regularly."
"2026-07-25 11:44:50","christinede-leon48@gmail.com","Yes","De Leon Christine A.","0122-0481","BS in Computer Science (BSCS)","2026","QA Tester / Technical Documentation Specialist","5","4","5","4","Python Java Git and Visual Studio Code","Cybersecurity fundamentals ethical hacking and network security tools","4","4","4","4","Occasional power fluctuation or loss of connection to local servers","Employed full-time as a Tech Professional","Very Confident","Maybe / Undecided","Overcoming complex recursive algorithm and data structure problems","Streamlining the rubric and criteria for Capstone project evaluation","Choose reliable capstone team members who share your work ethic."
"2026-07-25 12:56:03","joycealvarez35@gmail.com","Yes","Alvarez Joyce S.","0122-0352","BS in Information Technology (BSIT)","2026","UI/UX Designer / Frontend Developer","4","3","4","4","React Node.js JavaScript Python and Git","Modern frontend frameworks like React Next.js or Vue.js","3","3","4","3","Limited booking availability for computer labs during crunch weeks","Unemployed but actively applying for tech positions / Upskilling","Moderately Confident","Undecided","Building an end-to-end full-stack web application from scratch","Upgrading the computer lab reservation system to an online portal","Learn Git version control early—it will save your group projects."
"2026-07-25 14:10:22","maryjoyflores18@gmail.com","Yes","Flores Mary Joy T.","0122-0189","BS in Computer Science (BSCS)","2026","Lead Developer / Programmer","5","5","4","5","Python Java MySQL and REST API development principles","Cloud platforms like AWS or Google Cloud Docker and DevOps pipelines","4","5","3","4","Slow boot times on HDD-based workstations","Employed full-time as a Tech Professional","Extremely Confident","Yes definitely","Successfully debugging a critical memory leak and database sync issue","Standardizing and releasing defense schedules earlier","Don't rely solely on AI to write your code. Write logic yourself."`;

export function parseLSPUDataset() {
    const results = Papa.parse(embeddedCSVData, {
        header: true,
        skipEmptyLines: true
    });

    const records = results.data.map((row, index) => {
        // Standardize rating numbers
        const rateCore = parseInt(row['Rate Core Programming'] || row['Please rate the following aspects of your CCS academic journey (1 = Poor, 5 = Excellent). [Relevance of core programming concepts and math foundational theories.]'] || '4', 10);
        const rateElectives = parseInt(row['Rate Electives'] || row['Please rate the following aspects of your CCS academic journey (1 = Poor, 5 = Excellent). [Alignment of software electives and technologies taught with industry demand.]'] || '4', 10);
        const rateMentorship = parseInt(row['Rate Mentorship'] || row['Please rate the following aspects of your CCS academic journey (1 = Poor, 5 = Excellent). [Adequacy of mentorship provided during Capstone Project / Thesis development.]'] || '4', 10);
        const rateInternship = parseInt(row['Rate Internship'] || row['Please rate the following aspects of your CCS academic journey (1 = Poor, 5 = Excellent). [Value of the IT Internship / Practicum in exposing you to real dev environments.]'] || '4', 10);

        const rateHardware = parseInt(row['Rate Hardware Specs'] || '4', 10);
        const rateSoftware = parseInt(row['Rate Software IDEs'] || '4', 10);
        const rateInternet = parseInt(row['Rate Campus Internet'] || '3', 10);
        const rateAircon = parseInt(row['Rate Lab Cleanliness Aircon'] || '4', 10);

        const overallAvg = parseFloat(((rateCore + rateElectives + rateMentorship + rateInternship + rateHardware + rateSoftware + rateInternet + rateAircon) / 8).toFixed(2));

        // Determine basic sentiment score based on text responses & ratings
        let sentimentLabel = 'Positive';
        let sentimentScore = 0.85;

        const grievanceText = (row['Biggest Lab Grievance'] || '').toLowerCase();
        const breakthroughText = (row['Rewarding Breakthrough'] || '').toLowerCase();

        if (overallAvg < 3.5 || grievanceText.includes('slow') || grievanceText.includes('malfunction') || grievanceText.includes('strict')) {
            if (overallAvg < 3.2) {
                sentimentLabel = 'Negative';
                sentimentScore = 0.35;
            } else {
                sentimentLabel = 'Neutral';
                sentimentScore = 0.58;
            }
        }

        return {
            id: index + 1,
            name: row['Full Name'] || `Alumni #${index + 1}`,
            email: row['Email Address'] || `alumni${index + 1}@lspu.edu.ph`,
            studentId: row['Student ID'] || `0122-${1000 + index}`,
            program: row['Degree Program'] || 'BSIT',
            graduationYear: row['Year of Graduation'] || '2026',
            capstoneRole: row['Capstone Role'] || 'Developer',
            ratings: {
                coreProgramming: rateCore,
                electives: rateElectives,
                mentorship: rateMentorship,
                internship: rateInternship,
                hardware: rateHardware,
                software: rateSoftware,
                internet: rateInternet,
                labEnvironment: rateAircon,
                overallAvg
            },
            usefulTech: row['Useful Tech Taught'] || 'Python, Java',
            desiredTech: row['Missing Tech Desired'] || 'Docker, Cloud',
            grievance: row['Biggest Lab Grievance'] || 'None reported',
            employmentStatus: row['Employment Status'] || 'Employed full-time',
            confidence: row['Confidence Tech Interviews'] || 'Moderately Confident',
            guestSpeaker: row['Willing Guest Speaker'] || 'Undecided',
            breakthrough: row['Rewarding Breakthrough'] || 'Passing defense',
            restructureSuggestion: row['Restructure CCS Process'] || 'Standardize defense schedule',
            legacyTip: row['Legacy Tip For Freshmen'] || 'Learn Git early!',
            sentiment: {
                label: sentimentLabel,
                score: sentimentScore
            }
        };
    });

    return records;
}

export function computeDatasetSummary(records) {
    if (!records || records.length === 0) return null;

    const total = records.length;

    // Employment counts
    const employmentCounts = {
        fullTime: records.filter(r => r.employmentStatus.includes('full-time')).length,
        upskilling: records.filter(r => r.employmentStatus.includes('Unemployed') || r.employmentStatus.includes('Upskilling')).length,
        freelance: records.filter(r => r.employmentStatus.includes('Freelancing') || r.employmentStatus.includes('part-time')).length,
        furtherStudies: records.filter(r => r.employmentStatus.includes('certifications') || r.employmentStatus.includes('graduate')).length
    };

    // Program Breakdown
    const bsitCount = records.filter(r => r.program.includes('BSIT') || r.program.includes('Information Technology')).length;
    const bscsCount = records.filter(r => r.program.includes('BSCS') || r.program.includes('Computer Science')).length;

    // Sentiment Breakdown
    const positiveCount = records.filter(r => r.sentiment.label === 'Positive').length;
    const neutralCount = records.filter(r => r.sentiment.label === 'Neutral').length;
    const negativeCount = records.filter(r => r.sentiment.label === 'Negative').length;

    // Average Ratings
    const avgCore = (records.reduce((acc, r) => acc + r.ratings.coreProgramming, 0) / total).toFixed(2);
    const avgElectives = (records.reduce((acc, r) => acc + r.ratings.electives, 0) / total).toFixed(2);
    const avgMentorship = (records.reduce((acc, r) => acc + r.ratings.mentorship, 0) / total).toFixed(2);
    const avgInternship = (records.reduce((acc, r) => acc + r.ratings.internship, 0) / total).toFixed(2);
    const avgHardware = (records.reduce((acc, r) => acc + r.ratings.hardware, 0) / total).toFixed(2);
    const avgInternet = (records.reduce((acc, r) => acc + r.ratings.internet, 0) / total).toFixed(2);

    // Desired Tech Frequencies
    const techMap = {};
    records.forEach(r => {
        const desired = r.desiredTech || '';
        if (desired.toLowerCase().includes('docker')) techMap['Docker & Containers'] = (techMap['Docker & Containers'] || 0) + 1;
        if (desired.toLowerCase().includes('cloud') || desired.toLowerCase().includes('aws')) techMap['Cloud Computing (AWS/GCP)'] = (techMap['Cloud Computing (AWS/GCP)'] || 0) + 1;
        if (desired.toLowerCase().includes('react') || desired.toLowerCase().includes('vue') || desired.toLowerCase().includes('frontend')) techMap['Modern Web Frameworks'] = (techMap['Modern Web Frameworks'] || 0) + 1;
        if (desired.toLowerCase().includes('cybersecurity') || desired.toLowerCase().includes('security')) techMap['Cybersecurity & Networking'] = (techMap['Cybersecurity & Networking'] || 0) + 1;
        if (desired.toLowerCase().includes('ai') || desired.toLowerCase().includes('pytorch') || desired.toLowerCase().includes('tensorflow')) techMap['Deep Learning / AI Frameworks'] = (techMap['Deep Learning / AI Frameworks'] || 0) + 1;
        if (desired.toLowerCase().includes('flutter') || desired.toLowerCase().includes('mobile')) techMap['Mobile App Development'] = (techMap['Mobile App Development'] || 0) + 1;
    });

    const desiredTechArray = Object.keys(techMap).map(key => ({
        name: key,
        count: techMap[key]
    })).sort((a, b) => b.count - a.count);

    return {
        totalRecords: total,
        bsitCount,
        bscsCount,
        employmentCounts,
        sentimentCounts: {
            positive: positiveCount,
            neutral: neutralCount,
            negative: negativeCount,
            positivePct: Math.round((positiveCount / total) * 100)
        },
        averageRatings: {
            coreProgramming: parseFloat(avgCore),
            electives: parseFloat(avgElectives),
            mentorship: parseFloat(avgMentorship),
            internship: parseFloat(avgInternship),
            hardware: parseFloat(avgHardware),
            internet: parseFloat(avgInternet)
        },
        desiredTech: desiredTechArray
    };
}
